# Generated by Django 4.1.1 on 2022-10-13 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_username_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'managed': True, 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
