# Generated by Django 4.1.1 on 2022-10-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default='category-img/model6.jpg', upload_to='category-img'),
        ),
    ]
