# Generated by Django 4.1.1 on 2022-10-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_category_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(default='category-img/showcase6_6r6lH61.jpeg', upload_to='category-img'),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_img',
            field=models.ImageField(default='product/showcase6_6r6lH61.jpeg', upload_to='product'),
        ),
    ]
