# Generated by Django 4.1.2 on 2022-11-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_shipping_postal_code_remove_shipping_street_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='item_carted',
            field=models.IntegerField(default=1),
        ),
    ]
